Restaurant.create!([
	{name:"Odd Duck", address:"1201 S Lamar Blvd, Austin, TX 78704", photo:"http://cdn.cstatic.net/gridnailer/2000x/http://cdn.cstatic.net/images/gridfs/539e1962f92ea129c800160b/odd-duck-austin-2.jpg", website:"http://oddduckaustin.com/", comment:"Organic and fresh food, small dishes, relative expensive, but really nice atmosphere/vibe!", latitude:"", longitude:"", icon:"salad.png"},
	{name:"Justine’s Brasserie", address:"4710 E 5th St, Austin, TX 78702", photo:"http://cdn.c.photoshelter.com/img-get/I00001KWFV7HoDuc/s/750/750/brs-austin-028.jpg", website:"justines1937.com", comment:"Nice cocktail, kind relax and laid-back style", latitude:"", longitude:"", icon:"cocktail.png"},
	{name:"Dai Due", address:"2406 Manor Rd Ste A, Austin, TX 78722", photo:"http://cdn.archinect.net/images/1200x/2i/2iouf97yr9iixeag.jpg", website:"daidue.com", comment:"Originally a butcher shop, then they start to cook", latitude:"", longitude:"", icon:"steak.png"},
	{name:"Dolce Neve", address:"1713 S 1st St, Austin, TX 78704", photo:"http://www.dcarch.com/wp-content/uploads/2016/01/dolce-feat.jpg", website:"dolcenevegelato.com", comment:"Popular during summer night when everybody just want gelato and chat", latitude:"", longitude:"", icon:"ice-cream.png"},
	{name:"Pete’s Dueling Piano Bar", address:"421 E 6th St, Austin, TX 78701", photo:"https://www.vuevent.com/media/event_images/1435771544.97_kjbaskcjas.jpg", website:"petesduelingpianobar.com", comment:"Not sure whether they have in Dallas as well, a famous piano bar to go at Austin", latitude:"", longitude:"", icon:"beer.png"},
	{name:"Musashino Sushi Dokoro", address:"3407 Greystone Dr, Austin, TX 78731", photo:"http://musashinosushi.com/wp-content/uploads/musa4.jpg", website:"http://www.musashinosushi.com/", comment:"They r expensive, but they r really good sashimi and sushi!", latitude:"", longitude:"", icon:"m-sushi.png"},
	{name:"Uchi", address:"801 S Lamar Blvd, Austin, TX 78704", photo:"http://www.mweats.com/wp-content/uploads/2012/09/4W5C1466.jpg", website:"uchiaustin.com", comment:"Everybody who loves Japanese food knows the name...", latitude:"", longitude:"", icon:"u-sushi.png"},
	{name:"Caffe Medici", address:"1101 W Lynn St, Austin, TX 78703", photo:"http://austinot.com/wp-content/uploads/2012/05/browncoffeeco.jpg", website:"caffemedici.com", comment:"My personal favorite coffee shop at Austin. Quiet neighbourhood with great coffee!", latitude:"", longitude:"", icon:"coffee.png"},
	{name:"Ramen Tatsu-Ya", address:"8557 Research Blvd Ste 126, Austin, TX 78758", photo:"http://www.foodandwine.com/assets/images/201310-HD-best-ramen-shops-ramen-tatsu-ya.jpg/variations/original.jpg", website:"ramen-tatsuya.com", comment:"Best Ramen in the town, people wait in lines for it. Recommend sweet and sour Yoda for sides~", latitude:"", longitude:"", icon:"noodles.png"}
])